FROM eclipse-temurin:21-jdk-alpine

WORKDIR /app

# Copy maven wrapper and pom
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
# Resolve dependencies to speed up subsequent builds
RUN ./mvnw dependency:go-offline

# Copy source
COPY src ./src

# Expose Spring Boot port
EXPOSE 8080

# Run using the spring-boot maven plugin
CMD ["./mvnw", "spring-boot:run"]